### ISSUE TITLE
hi, where can i find ur paper?

### ISSUE THREAD

**Issue by northagain** [louisc-s/Machine-Learning-Technologies-on-EMG-for-Hand-Gesture-Recognition#3]
: )

**Comment by louisc-s** [comment]
Hey here is the link to it please cite me :)
https://drive.google.com/file/d/1vHzUKKFz1ifAaLOw91Sb41zo3zN5qRJl/view?usp=sharing

**Comment by northagain** [comment]
hello again, by clicking this link , i can only open this paper's cover for some reason.

**Comment by northagain** [comment]
oh, i solved it, thanks!
